#!/bin/bash


tomcat_host=3.83.10.21
tomcat_port=8080
tomcat_username=tomcat
tomcat_password=tomcat

context_path=VulnerableLab

curl -v -T target/*.war -u tomcat:tomcat 'http://'${tomcat_host}':'${tomcat_port}'/manager/text/deploy?path=/'${context_path}''

docker run -t owasp/zap2docker-stable zap-baseline.py -t 'http://'${tomcat_host}':'${tomcat_port}'/manager/text/deploy?path=/'${context_path}'' || true -g gen.conf -r testreport.html 

#docker exec zap zap-cli --verbose report -o /zap/reports/owasp-quick-scan-report.html --output-format html
